### ISSUE TITLE
Separate commands and queries

### ISSUE THREAD

**Issue by cstiitu** [ITU-BDSA2024-GROUP8/Chirp#60]
In order to separate commands and queries, as a developer, I can separate methods, which perform both queries and commands into multiple methods.

Acceptance criteria:

- We no longer methods, which both queried and perform an action.

**Comment by SneekySnek** [comment]
Separate Commands from Queries. Commands are procedures that have side effects. Queries are functions that return data. Every method should be either a Command or a Query, but not both.
